"""Add missing columns to analyses table

Revision ID: a4a4341cdaca
Revises: fa70208b4bfd
Create Date: 2025-04-19 01:49:53.949817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a4341cdaca'
down_revision = 'fa70208b4bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status_message', sa.String(length=255), nullable=True))

    with op.batch_alter_table('age_estimations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('status_message')
        batch_op.drop_column('progress')

    with op.batch_alter_table('age_estimations', schema=None) as batch_op:
        batch_op.drop_column('processed_image_path')

    # ### end Alembic commands ###
