"""Initial migration with fixed FaceTracking and relationship models

Revision ID: fa70208b4bfd
Revises: 
Create Date: 2025-04-19 01:13:27.200895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa70208b4bfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.Enum('IMAGE', 'VIDEO', 'UNKNOWN', name='contenttype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('thumbnail', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('content_id', sa.String(length=36), nullable=True),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('corrected_age', sa.Integer(), nullable=True),
    sa.Column('is_age_range_correct', sa.Boolean(), nullable=True),
    sa.Column('feedback_type', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('category_feedback', sa.JSON(), nullable=True),
    sa.Column('category_correct_values', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('validation_samples', sa.Integer(), nullable=True),
    sa.Column('epochs', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('weights_path', sa.String(length=255), nullable=True),
    sa.Column('used_feedback_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('frames_analyzed', sa.Integer(), nullable=True),
    sa.Column('frames_per_second', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('include_age_analysis', sa.Boolean(), nullable=True),
    sa.Column('overall_violence_score', sa.Float(), nullable=True),
    sa.Column('overall_adult_content_score', sa.Float(), nullable=True),
    sa.Column('overall_harassment_score', sa.Float(), nullable=True),
    sa.Column('overall_weapon_score', sa.Float(), nullable=True),
    sa.Column('overall_drug_score', sa.Float(), nullable=True),
    sa.Column('highest_risk_frame', sa.String(length=255), nullable=True),
    sa.Column('highest_risk_frame_timestamp', sa.Float(), nullable=True),
    sa.Column('highest_risk_score', sa.Float(), nullable=True),
    sa.Column('highest_risk_category', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('age_estimations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('frame_path', sa.String(length=255), nullable=True),
    sa.Column('frame_timestamp', sa.Float(), nullable=True),
    sa.Column('_face_location', sa.String(length=100), nullable=True),
    sa.Column('estimated_age', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('age_estimations_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('_detected_objects', sa.Text(), nullable=True),
    sa.Column('_age_estimations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('frame_path', sa.String(length=255), nullable=True),
    sa.Column('frame_timestamp', sa.Float(), nullable=True),
    sa.Column('violence_score', sa.Float(), nullable=True),
    sa.Column('adult_content_score', sa.Float(), nullable=True),
    sa.Column('harassment_score', sa.Float(), nullable=True),
    sa.Column('weapon_score', sa.Float(), nullable=True),
    sa.Column('drug_score', sa.Float(), nullable=True),
    sa.Column('_detected_objects', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('face_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('first_appearance', sa.Float(), nullable=False),
    sa.Column('last_appearance', sa.Float(), nullable=False),
    sa.Column('best_frame_path', sa.String(length=255), nullable=True),
    sa.Column('best_frame_number', sa.Integer(), nullable=True),
    sa.Column('best_frame_confidence', sa.Float(), nullable=True),
    sa.Column('total_appearances', sa.Integer(), nullable=True),
    sa.Column('best_age_estimation', sa.Float(), nullable=True),
    sa.Column('best_age_confidence', sa.Float(), nullable=True),
    sa.Column('face_features', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_tracking')
    op.drop_table('content_detections')
    op.drop_table('analysis_feedbacks')
    op.drop_table('age_estimations')
    op.drop_table('analysis_results')
    op.drop_table('analyses')
    op.drop_table('model_versions')
    op.drop_table('files')
    op.drop_table('feedback')
    op.drop_table('contents')
    # ### end Alembic commands ###
